### PR TITLE
Dependency updates

### LINKED ISSUE #74: Unable to install dependencies
Hi. I cloned the repo and I am trying to build the project but the npm goes into "loadIdealTree" step and is unable to install the dependencies. If I keep it open I get the following error:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

I am on Windows and would like to know if there is a specific npm version I should use to install the dependencies? I've also tried yarn but still unable to install the dependencies.

Would really love to look into the code and contribute but I need to get the project working first.

### PR DESCRIPTION
**Pull request by perry-mitchell**
Update some critical dependencies, React (16), React Native (0.54).

Dependencies before merging:
 * [x] https://github.com/jaysoo/react-native-prompt/pull/36 - react-native-prompt PropTypes fix
 * [x] Replacement of react-native-notification (dead package)
 * [x] https://github.com/facebook/react-native/issues/18223 - "Invalid response for blob" error
 * [x] Fix iOS tests
 * [x] Fix Jest
 * [x] Fix android tests
 * ~~Background colour for icons/images~~ (will be solved in a later MR)

Fixes #74 (Unable to install dependencies).

### CODE REVIEW

File: source/containers/RemoteConnectPage.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ import {
     isConnecting
 } from "../selectors/RemoteConnectPage.js";
 import {
-    getNotification as getDropboxAuthNotification,
+    // getNotification as getDropboxAuthNotification,
```
Comment (sallar) [inline source/containers/RemoteConnectPage.js]: Extra comment here

File: source/containers/RemoteConnectPage.js [hunk 2]
```diff
@@ -52,20 +52,20 @@ function handleConnectionCreation(dispatch, getState) {
...
     (state, ownProps) => ({
-        archiveType:            getArchiveType(state),
-        connecting:             isConnecting(state),
-        dropboxAuthenticated:   isAuthenticated(state),
-        dropboxAuthMessage:     getDropboxAuthNotification(state),
-        url:                    getRemoteURL(state),
+        archiveType: getArchiveType(state),
+        connecting: isConnecting(state),
+        dropboxAuthenticated: isAuthenticated(state),
+        // dropboxAuthMessage:     getDropboxAuthNotification(state),
```
Comment (sallar) [inline source/containers/RemoteConnectPage.js]: And here too

**Comment by perry-mitchell** [comment]
Sorted mate! @sallar
