### PR TITLE
Android back button handling

### LINKED ISSUE #64: Intermittent crashes when using back arrow
Sometimes app force closes upon backing out of a password. Usually when leaving app and coming back to it. So, view item, copy password, go to another app to use password, come back to buttercup app, tap back arrow to get back to list of password items, crash. Android 7.1.2. Nextcloud hosted archive. I wonder if this is just an issue with the password archive actually being locked whenever the app loses focus or something. ADB Logcat taken while issue happens is attached:
[issue.txt](https://github.com/buttercup/buttercup-mobile/files/1424705/issue.txt)

### LINKED ISSUE #65: Handle hardware back arrow
The hardware (or general Android) back arrow should be handled in-app. It should:

 * Dispatch a route-back action when touched on any page 1 level deep or more
 * Close the app (if possible?) if at the root page

### PR DESCRIPTION
**Pull request by perry-mitchell**
Fixes #64. Fixes #65.

The state is cleared when using the back button on the root screen - there's not much else to do as when android closes the app, the state is preserved but the native application reboots.

### CODE REVIEW

File: source/reducers/index.js [hunk 1]
```diff
@@ -21,4 +22,12 @@ const rootReducer = combineReducers({
     remoteExplorer
 });
 
+const rootReducer = (state, action) => {
+    if (action.type === APP_MASTER_RESET) {
+        // reset global state
+        state = undefined;
```
Comment (sallar) [inline source/reducers/index.js]: I think you have to return undefined instead of mutating the state here. Or is there a reason for this?

Comment (perry-mitchell) [reply source/reducers/index.js]: Actually it's just modifying the local variable. Setting state to undefined here doesn't mutate state 😊

Comment (perry-mitchell) [reply source/reducers/index.js]: I did take this example of a post online, hence the style.

Comment (perry-mitchell) [reply source/reducers/index.js]: It's also nice because the `APP_MASTER_RESET` action can still be listened to, if need-be.

Comment (sallar) [reply source/reducers/index.js]: Well if it works then probably its fine. I thought redux reducers need to return to set the state rather than setting value to it. But cool 😎👍
